### ISSUE TITLE
Body of file is being interpreted as metadata

### ISSUE THREAD

**Issue by Kevinpgalligan** [Flask-FlatPages/Flask-FlatPages#83] opened 2022-08-28 16:07 UTC
I believe recent versions have introduced a bug in the metadata parsing. Or at least, it's inconsistent with previous versions of the package. Wherever I have metadata at the top of a page, and the first line of the body ends with a colon, the first line is interpreted as a metadata field. The bug disappears when I revert to version 0.7.3 of Flask-FlatPages.

Example case:

    name: hello
    description: world
    
    Here are some items:
    * item 1
    * item 2

There will now be metadata under the keys "name", "description", and "Here are some items". I think it can be fixed by stopping the metadata parsing when an empty line is encountered, which should make it consistent with the old version.

**Comment by Kevinpgalligan** [comment] 2022-08-28 16:18
I imagine the bug is in this function:

https://github.com/Flask-FlatPages/Flask-FlatPages/blob/14579019ce975f7b164357e9e64b12b5419d1375/flask_flatpages/flatpages.py#L289

I would submit a patch myself, but I'm not familiar with the `yaml` package and I don't want to dig into it.

**Comment by lmmentel** [comment] 2022-11-16 15:29
I was experiencing the same problem and added `---` at the end of the metadata block and it worked for me. Your case would look like:

```
name: hello
description: world
---

Here are some items:
* item 1
* item 2
```

Hope it helps.

**Comment by emarsden** [comment] 2023-02-01 15:47
This is a problem with Markdown files that contain content such as 

```
foo: bar
bizzle: bazzle

[foo]: bar
```

This generates a `yaml.constructor.ConstructorError` ("found unhashable key") when accessing the page metadata. If it's inconvenient to modify the source files as in @Immentel's workaround, it's possible to use the legacy metadata parser with: 

```
app.config["FLATPAGES_LEGACY_META_PARSER"] = True
pages = FlatPages(app)
```

**Comment by padraic-padraic** [comment] 2023-02-01 21:03
Both the suggestions mentioned here, switching the legacy parser or indeed adding an explicit `---` or `...` to close the document, will work. But it does seem the parser is a bit over-eager at the moment. I'll leave this issue open, these are some great test fixtures we can use to iron out the kinks!

**Comment by padraic-padraic** [comment] 2023-11-04 22:40
Hello all,

I've played with this on and off over the months and I can't find a satisfactory way to prevent this behaviour. Simply put, if you have a later token that looks like valid YAML, it's not clear how to tell the parser "this newline is just part of my metadata" versus "this newline means stop parsing".

Simply put, the `_libyaml_parser` is much more capable; it allows you to use a lot more YAML features in front matter, such as multi-line strings, and tries to preserve the old "terminate metadata with a newline" behaviour as much as possible.

However, I note that most other frameworks like Jekyll, Obsidian, Zola, Hugo etc all require explicit closing blocks for frontmatter, so I don't think requiring a closing block in some cases is a heavy price to pay.

The docs could and should be a lot clearer about this, so I appreciate the feedback!

**Comment by Kevinpgalligan** [comment] 2023-11-05 00:05
Perhaps this should be marked as "will-not-fix" rather than "completed", since it hasn't been addressed that the default parser is backwards-incompatible and can cause unexpected changes for users of previous versions. That's a regression / bug, to my mind.

A suggestion: reopen this issue, or create another one, to make sure that the documentation is updated to reflect that a separator should be added after the metadata. As it stands, new users could still get caught out by this, as the examples in the docs do not include a separator. I would send a pull request to update the docs but do not currently have computer access.

**Comment by padraic-padraic** [comment] 2023-11-06 11:45
I appreciate your point; I'm going to cut a new release shortly with a bugfix, some operational improvements, and restored documentation. I'll re-open the issue, please let me know if the changes seem satisfactory!

Regarding your point, I don't consider it a regression. Issue #59  or the submitted PRs #64 and #75 show some of the reasons I decided to tweak the way we handle the metadata. But I appreciate it needed better signposting, perhaps with a major version bump rather than a minor.

**Comment by Kevinpgalligan** [comment] 2023-11-08 18:26
Looks good! Should prevent future users from having any problems.

**Comment by padraic-padraic** [comment] 2023-11-08 20:58
Closing as wont-fix just to be explicit that this is expected behaviour from the parser change.

**Closed** 2024-01-16 10:13 UTC
